### ISSUE TITLE
Callback never get called

### ISSUE THREAD

**Issue by TimeyWimey** [STRML/textFit#22]
Seems like you don't call callback at the end

**Comment by STRML** [comment]
That's true. At some point this was changed from an asynchronous library to a synchronous one and the callback is no longer necessary. Simply continue working in the same scope after calling textFit().

**Comment by STRML** [comment]
Fixed in https://github.com/STRML/textFit/commit/3dea45193e3b8b80a9b95daf0379fb4f49cc37a9
