### ISSUE TITLE
Text shrinks more than necessary (AKA no odd font-sizes?)

### ISSUE THREAD

**Issue by Mesoptier** [STRML/textFit#26]
I am trying to fit a single line of text (`{ minFontSize: 16, maxFontSize: 30 }`). But the text is often smaller than it needs to be, and when I increase the `font-size` property by `1px` it still fits in the container. The library seems to skip odd font-sizes for some reason. 

I suspect the binary search algorithm may be the problem.

**Comment by alpha-and-omega** [comment]
Yes, there is a bug. I have fixed this bug in my local copy.
Should I pull the fix ?

**Comment by billewanick** [comment]
@alpha-and-omega yes please!!

**Comment by alpha-and-omega** [comment]
here is the gist: https://gist.github.com/alpha-and-omega/2bafcc5ef77e81d3fd45ee82d2b5a236

**Comment by ahobsonsayers** [comment]
@alpha-and-omega reckon you could submit a pull request with your edits? Would be great to have the fix in the official release

**Comment by alpha-and-omega** [comment]
You are free to apply it without pull request.

**Comment by ahobsonsayers** [comment]
I realise that, I'm more just thinking if it became official it could help more people instead of them having to look in the issues to find the fix and apply it themselves.

If you'd prefer I could open the pull request with your changes myself if you gave permission.

**Comment by alpha-and-omega** [comment]
Yes, please create pull request.

**Comment by STRML** [comment]
Thanks, fixed in latest.
