### ISSUE TITLE
Doesn't work properly in Safari

### ISSUE THREAD

**Issue by KevinMars** [STRML/textFit#28]
It works only half the time in safari,

**Comment by STRML** [comment]
What about the other half the time?

**Comment by KevinMars** [comment]
Thanks for getting back to me. 

Sorry, I should be more clear. Textfit doesn't work properly when the page first loads but when something is clicked on the page and textfit is called again then it works fine. By properly, I mean it enlarges the text but not nearly enough to fit the div. 

Please see this url for an example, http://www.heyfable.co/product_page.html?Headphones
- move the multicolored slider near the top of the page to see it work properly after

Problem exists on safari, not on firefox or chrome

**Comment by KevinMars** [comment]
Hi I fixed the problem by wrapping it in a window.onload() function. I removed the url because I want to keep it private for now, but if you want to see the problem in action let me know. Thanks!
