### ISSUE TITLE
Example page doesn't work (Wrong link?)

### ISSUE THREAD

**Issue by remonator** [STRML/textFit#42]
The example page mentioned in README ([links to this page](http://strml.github.com/examples/textFit.html)) does not show resized text, all text samples appear very tiny.

Tested with Firefox 76.0 and Edge (Chromium) Version 81.0.416.72 (Official build) (64-bit)

Note: It works correctly on [this page](https://textfit.strml.net/examples/textFit.html), although this page's certificate is expired.

**Comment by remonator** [comment]
The link to the example page in README looks like this:

![image](https://user-images.githubusercontent.com/54318829/95853215-5850be80-0d55-11eb-86f5-e10b68a4adb2.png)

**Comment by STRML** [comment]
Thanks!
